heading_estimators:

  # The available altitude estimators
  heading_estimators: [
    "PIXHAWK",
    "GYRO",
    "COMPASS",
    "OPTFLOW", 
    "HECTOR",
    "BRICK",
    "VIO",
    "VSLAM",
    "ICP",
    "BRICKFLOW",
    "ALOAM",
    "ALOAMREP",
    "LIOSAM",
  ] 

  # The measured states of the model
  model_states: [
    "HDG", 
    "HDG_RATE", 
    "HDG_ACC" 
  ] 

  # The available measurements
  measurements: [
    "hdg_compass",
    "rate_gyro",
    "rate_optflow",
    "rate_liosam",
    "hdg_hector",
    "hdg_brick",
    "hdg_vio",
    "hdg_vslam",
    "rate_icp",
    "hdg_aloam",
    "hdg_liosam",
  ]

  # The fused measurements for each state estimator
  fused_measurements:
    PIXHAWK: []
    GYRO: ["rate_gyro"]
    COMPASS: ["rate_gyro", "hdg_compass"]
    OPTFLOW: ["rate_gyro", "rate_optflow"]
    HECTOR: ["rate_gyro", "hdg_hector"]
    BRICK: ["rate_gyro", "hdg_brick"]
    VIO: ["rate_gyro", "hdg_vio"]
    VSLAM: ["rate_gyro", "hdg_vslam"]
    ICP: ["rate_icp"]
    BRICKFLOW: ["rate_gyro", "hdg_brick"]
    ALOAM: ["rate_gyro", "hdg_aloam", "rate_icp"]
    ALOAMREP: ["rate_gyro", "hdg_aloam", "rate_icp"]
    LIOSAM: ["hdg_liosam", "rate_liosam"]

  # Mapping of measurements to states
  measurement_states:
    hdg_compass: HDG
    rate_gyro: HDG_RATE
    rate_optflow: HDG_RATE
    rate_liosam: HDG_RATE
    hdg_hector: HDG
    hdg_brick: HDG
    hdg_vio: HDG
    hdg_vslam: HDG
    rate_icp: HDG_RATE
    hdg_aloam: HDG
    hdg_liosam: HDG

  # Mapping states to model
  state_mapping:
    HDG: [1.0, 0.0, 0.0]
    HDG_RATE: [0.0, 1.0, 0.0]
    HDG_ACC: [0.0, 0.0, 1.0]

