state_estimators:

  # The number of model states
  n_model_states: 3

  # The available state estimators
  state_estimators: [
    "OPTFLOW", 
    "GPS", 
    "OPTFLOWGPS",
    "RTK",
    "VIO",
    "BRICK",
    "T265",
    "HECTOR",
    "BRICKFLOW",
    "VSLAM",
    "ICP",
    "ALOAM",
    "ALOAMGARM",
    "ALOAMREP",
    "LIOSAM",
    "UWB",
    "DUMMY",
  ] 

  # The measured states of the model
  model_states: [
    "POSITION", 
    "VELOCITY", 
    "ACCELERATION", 
  ] 

  # The available measurements
  measurements: [
    "vel_optflow",
    "pos_mavros",
    "vel_mavros",
    "pos_rtk",
    "vel_rtk",
    "pos_vio",
    "vel_vio",
    "pos_brick",
    "vel_brick",
    "pos_hector",
    "pos_vslam",
    "vel_icp",
    "pos_aloam",
    "pos_liosam",
    "vel_liosam",
    "pos_uwb",
    "acc_imu",
  ]

  # The fused measurements for each state estimator
  fused_measurements:
    OPTFLOW: ["vel_optflow"]
    GPS: ["pos_mavros"]
    OPTFLOWGPS: ["vel_optflow", "pos_mavros"]
    RTK: ["pos_rtk", "vel_mavros"]
    HECTOR: ["pos_hector"]
    VIO: ["pos_vio", "vel_vio"]
    VSLAM: ["pos_vslam"]
    BRICK: ["pos_brick"]
    BRICKFLOW: ["vel_optflow", "pos_brick"]
    T265: []
    ICP: ["vel_icp"]
    ALOAM: ["pos_aloam", "vel_icp"]
    ALOAMGARM: ["pos_aloam", "vel_icp"]
    ALOAMREP: ["pos_aloam", "vel_icp"]
    LIOSAM: ["pos_liosam", "vel_liosam"]
    UWB: ["pos_uwb"]
    DUMMY: []

  # Mapping of measurements to states
  measurement_states:
    vel_optflow: VELOCITY
    pos_mavros: POSITION
    vel_mavros: VELOCITY
    pos_rtk: POSITION
    vel_rtk: VELOCITY
    pos_vio: POSITION
    vel_vio: VELOCITY
    pos_brick: POSITION
    vel_brick: VELOCITY
    pos_hector: POSITION
    pos_vslam: POSITION
    vel_icp: VELOCITY
    pos_aloam: POSITION
    pos_liosam: POSITION
    vel_liosam: VELOCITY
    pos_uwb: POSITION
    acc_imu: ACCELERATION

  # Mapping states to model
  state_mapping:
    POSITION: [1.0, 0.0, 0.0]
    VELOCITY: [0.0, 1.0, 0.0]
    ACCELERATION: [0.0, 0.0, 1.0]
