# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "ALOAMREP"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "ALOAMREP"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "ALOAMREP"

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["ALOAMREP"]

heading_estimators:
  active: ["GYRO", "ALOAMREP"]

altitude_estimators: 
  active: ["ALOAMREP", "BARO", "HEIGHT"] 

lateral:
  slam:
    use_general_slam_origin: true # use slam_origin instead of aloam_origin/liosam_origin

# Process covariance
  Q: [1, 0, 0,
      0, 1, 0,
      0, 0, 1]

# Covariances of measurements
  R:
    pos_aloam: [1]
