# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "LIOSAM"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "LIOSAM"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "LIOSAM" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["LIOSAM"]

  publish_tf:
    LIOSAM: false

heading_estimators:
  active: ["GYRO", "LIOSAM"]

altitude_estimators: 
  active: ["HEIGHT", "BARO", "LIOSAM"] 

lateral:
  slam:
    use_general_slam_origin: true # use slam_origin instead of aloam_origin/liosam_origin

  # Covariances of measurements
  R:
    pos_liosam: [10]
    vel_liosam: [10]

heading:
  # Covariances of measurements
  R:
    hdg_liosam: [0.1]
    rate_liosam: [10]

altitude:
  R:
    height_liosam: [10000]
    vel_liosam_z: [1000.0]

