# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "VIO"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "VIO"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "VIO" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["VIO"]

heading_estimators:
  # active: ["PIXHAWK", "GYRO", "VIO"]
  active: ["VIO"]
