# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "ALOAMREP"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "ALOAMREP"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "ALOAMREP" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["ALOAMREP", "GPS"]

  publish_tf:
    ALOAM: true

heading_estimators:
  active: ["PIXHAWK", "GYRO", "ALOAMREP"]

lateral:
  slam:
    use_general_slam_origin: true # use slam_origin instead of aloam_origin/liosam_origin
