# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "LIOSAM"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "LIOSAM"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "LIOSAM" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["LIOSAM"]

heading_estimators:
  active: ["GYRO", "LIOSAM"]

lateral:
  # Covariances of measurements
  R:
    pos_liosam: [10]

heading:
  # Covariances of measurements
  R:
    hdg_liosam: [0.1]

altitude:
  R:
    height_liosam: [1]

# Publishing of TF of each estimator can be disabled (default is enabled):
state_estimators:
  publish_tf:
    LIOSAM: false
