# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "VSLAM"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "VSLAM" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["GPS", "VSLAM"]

heading_estimators:
  active: ["PIXHAWK", "GYRO", "VSLAM"]

altitude_estimators: 
  active: ["HEIGHT", "VIO", "BARO"] 
